### ISSUE TITLE
Make it mobile responsive

### ISSUE THREAD

**Issue by ankitjain28may** [ankitjain28may/urlshortner#2]
As you can see, it isn't mobile responsive.. so need to fix that
![screenshot-2017-10-24 pagespeed insights 2](https://user-images.githubusercontent.com/14014254/31952475-465a7c4c-b8fe-11e7-8f16-5fa5160f6bc1.png)

**Comment by danidee10** [comment]
@ankitjain28may I'm interested in this issue.

Would you want a complete rewrite in bootstrap ?

Or you're fine with CSS3 media queries

**Comment by ankitjain28may** [comment]
@danidee10 You can use media queries

**Comment by danidee10** [comment]
Alright i'm on it

**Comment by marcosstefani** [comment]
Can I work on this?

**Comment by ankitjain28may** [comment]
@danidee10 is already working on it.

**Comment by marcosstefani** [comment]
Done.

**Comment by marcosstefani** [comment]
Please, if it is concluded, please close the issue.
